In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
l=[11,22,33,44]
ar=np.array(l)

In [6]:
ar

array([11, 22, 33, 44])

In [5]:
type(ar)

numpy.ndarray

In [14]:
li=[11,22,33,44]
ar=np.array(li)
ar[0:4]

array([11, 22, 33, 44])

In [20]:
ls=[[1,2,3,4],[22,33,44,55]]
arr=np.array(ls)
arr

array([[ 1,  2,  3,  4],
       [22, 33, 44, 55]])

In [19]:
arr
#arr[rows,columns]
arr[0:2,0:2]

array([[ 1,  2],
       [22, 33]])

In [26]:
for o in range(0,10+1,2):
    print(o, end=" ")

0 2 4 6 8 10 

In [27]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

In [31]:
np.zeros(4)

array([0., 0., 0., 0.])

In [35]:
import random

np.random.randint(1,100,5)

array([77, 61, 34, 22, 76])

In [50]:
i=np.arange(1,10).reshape(3,3)
i

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
i.shape

(3, 3)

In [47]:
i.max()

9

In [48]:
i.min()

1

In [49]:
i.argmax()

8

In [51]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [53]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
import pandas as pd
import numpy as np

l = [1.,3.,5.6,6.7,7.]
pd.Series(l, index = [10, 11, 12, 13, 14])

10    1.0
11    3.0
12    5.6
13    6.7
14    7.0
dtype: float64

In [56]:
l1=[[2,3,4],[5,6,7],[8,9,10]]

In [58]:
pd.DataFrame(l1, index=['A','B','C'], columns=['X','Y','Z'])

X  Y   Z
A  2  3   4
B  5  6   7
C  8  9  10

In [59]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])  

In [60]:
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan']) 

In [61]:
ser1+ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

In [62]:
from numpy.random import randn
np.random.seed(101)
#df = pd.DataFrame(randn(5,4))
df = pd.DataFrame(randn(5,4),index=['A', 'B', 'C', 'D', 'E'],columns='W X Y Z'.split())

In [63]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [64]:
df['next']=df['X']

In [66]:
df['X']

A    0.628133
B   -0.319318
C    0.740122
D   -0.758872
E    1.978757
Name: X, dtype: float64

In [67]:
df['next']=df['X']**2

In [68]:
df

W         X         Y         Z      next
A  2.706850  0.628133  0.907969  0.503826  0.394551
B  0.651118 -0.319318 -0.848077  0.605965  0.101964
C -2.018168  0.740122  0.528813 -0.589001  0.547781
D  0.188695 -0.758872 -0.933237  0.955057  0.575887
E  0.190794  1.978757  2.605967  0.683509  3.915481

In [70]:
df.drop('next',axis=1,inplace=True)

In [71]:
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [72]:
df.loc['B']

W    0.651118
X   -0.319318
Y   -0.848077
Z    0.605965
Name: B, dtype: float64

In [73]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

In [74]:
df.iloc[:2]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965

In [75]:
df[df>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [78]:
df[df['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [81]:
df = pd.DataFrame({'A':[1,2,np.nan],
                  'B':[5,np.nan,np.nan],
                  'C':[1,2,3]})

In [82]:
df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [83]:
df.dropna()

A    B  C
0  1.0  5.0  1

In [84]:
df.isnull().sum()

A    1
B    2
C    0
dtype: int64

In [89]:
import pandas as pd
df=pd.read_csv(r'C:\Users\Lenovo\Desktop\DataScience Bootcamp\heights_few_samples')

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Lenovo\\Desktop\\DataScience Bootcamp\\heights_few_samples'